// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RewardsCounter.Api.Repositories.Data;

#nullable disable

namespace RewardsCounter.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RewardsCounter.Api.Repositories.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            CreationDate = new DateTime(2018, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ilya"
                        },
                        new
                        {
                            Id = new Guid("99135b8d-cda6-493a-8994-6faecd21bf48"),
                            CreationDate = new DateTime(2020, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivan"
                        },
                        new
                        {
                            Id = new Guid("3b217a1d-c7d9-40da-a4d4-14e4c3a2ae2b"),
                            CreationDate = new DateTime(2020, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ann"
                        },
                        new
                        {
                            Id = new Guid("de632b7e-627d-4bfe-9f96-edc290d32bbe"),
                            CreationDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("002f9c00-7523-44f1-ab9e-f906f368ab17"),
                            CreationDate = new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Liam"
                        },
                        new
                        {
                            Id = new Guid("ee884543-1b4e-46f9-a652-575aa9570f01"),
                            CreationDate = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("fa05b53c-da5e-4a30-9751-744afdcc5198"),
                            CreationDate = new DateTime(2022, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oliver"
                        },
                        new
                        {
                            Id = new Guid("b5280851-7383-49d0-8375-e98f84e1ce3b"),
                            CreationDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amelia"
                        },
                        new
                        {
                            Id = new Guid("7203c9dd-6778-435e-8788-ce3532393fd0"),
                            CreationDate = new DateTime(2021, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emma"
                        });
                });

            modelBuilder.Entity("RewardsCounter.Api.Repositories.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81089cf3-1eeb-4477-afe6-4f7141854a56"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("74b9fcf0-6deb-490f-907e-808f5513a076"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 1.3m,
                            Timestamp = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10709443-1321-4d0c-9514-1492490af67c"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 100m,
                            Timestamp = new DateTime(2020, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e5d17ba3-55a8-4a27-8881-97684409b31f"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("362762c5-a5b0-422b-bc16-45d7ecfe4e8b"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("043fbb79-3560-4513-873d-1d2add5da8b4"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("26d3b846-b2da-4868-87d1-23ed689d5be1"),
                            ClientId = new Guid("99135b8d-cda6-493a-8994-6faecd21bf48"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("71e8c012-2e1c-4ab5-b4dd-53d7bbf1d1f0"),
                            ClientId = new Guid("99135b8d-cda6-493a-8994-6faecd21bf48"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3e4a82ef-8d95-4d46-b8c5-52a767513386"),
                            ClientId = new Guid("99135b8d-cda6-493a-8994-6faecd21bf48"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dfa89f9b-47a4-4b33-8c8a-e8ec41a170d6"),
                            ClientId = new Guid("99135b8d-cda6-493a-8994-6faecd21bf48"),
                            Sum = 50m,
                            Timestamp = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("943134af-7345-4e48-8d0b-7605bbd8f99c"),
                            ClientId = new Guid("3b217a1d-c7d9-40da-a4d4-14e4c3a2ae2b"),
                            Sum = 130m,
                            Timestamp = new DateTime(2021, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("46d5e8c1-bdcb-4f35-b8ea-508dc2dfe18a"),
                            ClientId = new Guid("3b217a1d-c7d9-40da-a4d4-14e4c3a2ae2b"),
                            Sum = 12m,
                            Timestamp = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b5dbfa05-8427-4a0c-9c11-48f96cfa3b0a"),
                            ClientId = new Guid("3b217a1d-c7d9-40da-a4d4-14e4c3a2ae2b"),
                            Sum = 51m,
                            Timestamp = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("83931490-dda8-4abd-801d-de5db8bfbff6"),
                            ClientId = new Guid("de632b7e-627d-4bfe-9f96-edc290d32bbe"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2c976ae-e01a-4c7d-a0e8-00adadf3a768"),
                            ClientId = new Guid("de632b7e-627d-4bfe-9f96-edc290d32bbe"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c87e3ce6-61e7-454e-90d6-45e6143ed917"),
                            ClientId = new Guid("de632b7e-627d-4bfe-9f96-edc290d32bbe"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c9b540b-3464-4cbc-a500-9defd3f8b969"),
                            ClientId = new Guid("de632b7e-627d-4bfe-9f96-edc290d32bbe"),
                            Sum = 50m,
                            Timestamp = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("929fc6e8-223f-4d09-9e79-34a079f69a03"),
                            ClientId = new Guid("de632b7e-627d-4bfe-9f96-edc290d32bbe"),
                            Sum = 50m,
                            Timestamp = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6130c7f5-9cd2-4c3b-9e2b-455f38effff7"),
                            ClientId = new Guid("002f9c00-7523-44f1-ab9e-f906f368ab17"),
                            Sum = 120m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("520ab412-3b2e-4db5-9c52-3bdda7abcb19"),
                            ClientId = new Guid("fa05b53c-da5e-4a30-9751-744afdcc5198"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dfde73ed-180d-45ae-9ff6-66a7dd39de70"),
                            ClientId = new Guid("b96c7e78-46bd-4057-8990-e3d2f82e0e8b"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("78c32232-07fc-4fc4-ade8-d95c9de211f2"),
                            ClientId = new Guid("b5280851-7383-49d0-8375-e98f84e1ce3b"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("60ab9b4f-84c6-4e35-bba4-24356ebb9d67"),
                            ClientId = new Guid("7203c9dd-6778-435e-8788-ce3532393fd0"),
                            Sum = 12.3m,
                            Timestamp = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("17e243a6-c450-4d2c-9115-06f793c8818b"),
                            ClientId = new Guid("7203c9dd-6778-435e-8788-ce3532393fd0"),
                            Sum = 40m,
                            Timestamp = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0b543c3c-6330-4c8b-953a-183d9879f96e"),
                            ClientId = new Guid("7203c9dd-6778-435e-8788-ce3532393fd0"),
                            Sum = 100m,
                            Timestamp = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c4574704-626d-49bf-bc2f-9877331f1c2a"),
                            ClientId = new Guid("7203c9dd-6778-435e-8788-ce3532393fd0"),
                            Sum = 50m,
                            Timestamp = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
